
name: CI-CD Monitoring

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      # (Facultatif) Vérifier les versions préinstallées
      - name: Check Docker & Compose
        run: |
          docker --version
          docker compose version

      - name: Build de l'image Flask
        run: docker build -t flask-monitoring-app .

      - name: Test de l'application Flask
        run: |
          docker run -d --name flask-monitor -p 5000:5000 flask-monitoring-app
          # attendre que l'appli démarre
          sleep 5
          bash test_app.sh
          # nettoyer
          docker logs flask-monitor || true
          docker rm -f flask-monitor || true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      # Ajoute ici tes étapes de déploiement (scp, ssh, kubectl, etc.)
